# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my5.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import vtk
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from vtk.util.numpy_support import numpy_to_vtk, vtk_to_numpy



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1766, 956)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadcaseBTN = QtWidgets.QPushButton(self.centralwidget)
        self.loadcaseBTN.setGeometry(QtCore.QRect(760, 340, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.loadcaseBTN.setFont(font)
        self.loadcaseBTN.setObjectName("loadcaseBTN")
        self.saveBTN = QtWidgets.QPushButton(self.centralwidget)
        self.saveBTN.setGeometry(QtCore.QRect(1320, 830, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.saveBTN.setFont(font)
        self.saveBTN.setObjectName("saveBTN")
        self.TransX_slider = QtWidgets.QSlider(self.centralwidget)
        self.TransX_slider.setGeometry(QtCore.QRect(880, 580, 861, 16))
        self.TransX_slider.setMinimum(-180)
        self.TransX_slider.setMaximum(180)
        self.TransX_slider.setOrientation(QtCore.Qt.Horizontal)
        self.TransX_slider.setObjectName("TransX_slider")
        self.TransY_slider = QtWidgets.QSlider(self.centralwidget)
        self.TransY_slider.setGeometry(QtCore.QRect(880, 620, 861, 16))
        self.TransY_slider.setMinimum(-180)
        self.TransY_slider.setMaximum(180)
        self.TransY_slider.setOrientation(QtCore.Qt.Horizontal)
        self.TransY_slider.setObjectName("TransY_slider")
        self.RotX_slider = QtWidgets.QSlider(self.centralwidget)
        self.RotX_slider.setGeometry(QtCore.QRect(880, 700, 861, 16))
        self.RotX_slider.setMinimum(-180)
        self.RotX_slider.setMaximum(180)
        self.RotX_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RotX_slider.setObjectName("RotX_slider")
        self.RotY_slider = QtWidgets.QSlider(self.centralwidget)
        self.RotY_slider.setGeometry(QtCore.QRect(880, 740, 861, 16))
        self.RotY_slider.setMinimum(-180)
        self.RotY_slider.setMaximum(180)
        self.RotY_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RotY_slider.setObjectName("RotY_slider")
        self.RotZ_slider = QtWidgets.QSlider(self.centralwidget)
        self.RotZ_slider.setGeometry(QtCore.QRect(880, 780, 861, 16))
        self.RotZ_slider.setMinimum(-180)
        self.RotZ_slider.setMaximum(180)
        self.RotZ_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RotZ_slider.setObjectName("RotZ_slider")
        self.TransX_label = QtWidgets.QLabel(self.centralwidget)
        self.TransX_label.setGeometry(QtCore.QRect(780, 570, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.TransX_label.setFont(font)
        self.TransX_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TransX_label.setObjectName("TransX_label")
        self.TransY_label = QtWidgets.QLabel(self.centralwidget)
        self.TransY_label.setGeometry(QtCore.QRect(780, 610, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.TransY_label.setFont(font)
        self.TransY_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TransY_label.setObjectName("TransY_label")
        self.RotX_label = QtWidgets.QLabel(self.centralwidget)
        self.RotX_label.setGeometry(QtCore.QRect(780, 690, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.RotX_label.setFont(font)
        self.RotX_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RotX_label.setObjectName("RotX_label")
        self.RotY_label = QtWidgets.QLabel(self.centralwidget)
        self.RotY_label.setGeometry(QtCore.QRect(780, 730, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.RotY_label.setFont(font)
        self.RotY_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RotY_label.setObjectName("RotY_label")
        self.RotZ_label = QtWidgets.QLabel(self.centralwidget)
        self.RotZ_label.setGeometry(QtCore.QRect(780, 770, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.RotZ_label.setFont(font)
        self.RotZ_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RotZ_label.setObjectName("RotZ_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 580, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 620, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 700, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 740, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(660, 780, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.updateBTN = QtWidgets.QPushButton(self.centralwidget)
        self.updateBTN.setGeometry(QtCore.QRect(930, 830, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.updateBTN.setFont(font)
        self.updateBTN.setObjectName("updateBTN")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 600, 600))
        self.widget.setObjectName("widget")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 581, 201))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 390, 581, 201))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_fluro = QtWidgets.QLabel(self.centralwidget)
        self.label_fluro.setGeometry(QtCore.QRect(1000, 20, 380, 380))
        self.label_fluro.setText("")
        self.label_fluro.setScaledContents(True)
        self.label_fluro.setObjectName("label_fluro")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1130, -20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.TransY_slider_2 = QtWidgets.QSlider(self.centralwidget)
        self.TransY_slider_2.setGeometry(QtCore.QRect(880, 660, 861, 16))
        self.TransY_slider_2.setMinimum(-180)
        self.TransY_slider_2.setMaximum(180)
        self.TransY_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.TransY_slider_2.setObjectName("TransY_slider_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(660, 660, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.TransZ_label = QtWidgets.QLabel(self.centralwidget)
        self.TransZ_label.setGeometry(QtCore.QRect(780, 650, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.TransZ_label.setFont(font)
        self.TransZ_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TransZ_label.setObjectName("TransZ_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.frame_1 = QtWidgets.QFrame()
        self.vtkWidget_1 = QVTKRenderWindowInteractor(self.frame_1)
        self.formLayout.addWidget(self.vtkWidget_1)

        self.ren_1 = vtk.vtkRenderer()
        self.vtkWidget_1.GetRenderWindow().AddRenderer(self.ren_1)
        self.iren_1 = self.vtkWidget_1.GetRenderWindow().GetInteractor()

        self.frame_2 = QtWidgets.QFrame()
        self.vtkWidget_2 = QVTKRenderWindowInteractor(self.frame_2)
        self.formLayout_2.addWidget(self.vtkWidget_2)

        self.ren_2 = vtk.vtkRenderer()
        self.vtkWidget_2.GetRenderWindow().AddRenderer(self.ren_2)
        self.iren_2 = self.vtkWidget_2.GetRenderWindow().GetInteractor()

        self.frame_3 = QtWidgets.QFrame()
        self.vtkWidget_3 = QVTKRenderWindowInteractor(self.frame_3)
        self.formLayout_3.addWidget(self.vtkWidget_3)

        self.ren_3 = vtk.vtkRenderer()
        self.vtkWidget_3.GetRenderWindow().AddRenderer(self.ren_3)
        self.iren_3 = self.vtkWidget_3.GetRenderWindow().GetInteractor()


        self.PNG_Reader_1 = vtk.vtkPNGReader()
        self.PNG_Reader_1.SetNumberOfScalarComponents(1)
        self.PNG_Reader_1.SetFileDimensionality(3)
        self.PNG_Reader_1.SetDataExtent(0, 200, 0, 200, 0, 199)
        self.PNG_Reader_1.SetFilePrefix(r'C:\Users\vision2110\Desktop\chinghui\subject1\bone_resize\L1/')
        self.PNG_Reader_1.SetFilePattern("%s%d.png")
        self.PNG_Reader_1.Update()
        self.PNG_Reader_1.SetDataByteOrderToLittleEndian()

        self.PNG_contour_1 = vtk.vtkDiscreteMarchingCubes()
        self.PNG_contour_1.SetInputConnection(self.PNG_Reader_1.GetOutputPort())
        self.PNG_contour_1.ComputeNormalsOn()
        self.PNG_contour_1.SetValue(0, 255)

        self.PNG_sinc_1 = vtk.vtkWindowedSincPolyDataFilter()
        self.PNG_sinc_1.SetInputConnection(self.PNG_contour_1.GetOutputPort())
        self.PNG_sinc_1.SetNumberOfIterations(50)
        self.PNG_sinc_1.SetPassBand(0.003)

        PNG_mapper_1 = vtk.vtkPolyDataMapper()
        PNG_mapper_1.SetInputConnection(self.PNG_sinc_1.GetOutputPort())
        PNG_mapper_1.ScalarVisibilityOff()

        PNG_actor_1 = vtk.vtkActor()
        PNG_actor_1.SetMapper(PNG_mapper_1)

        PNG_renderer_1 = vtk.vtkRenderer()
        PNG_renderer_1.SetBackground([0.1, 0.1, 0.1])
        PNG_renderer_1.AddActor(PNG_actor_1)

        cameraR_1 = vtk.vtkCamera()
        cameraR_1.SetPosition(0, 1000, 0)
        cameraR_1.SetFocalPoint(0, 0, 0)
        cameraR_1.SetViewUp(0, 0, -1.0)

        self.ren_1.SetActiveCamera(cameraR_1)
        self.ren_1.AddActor(PNG_actor_1)
        self.ren_1.ResetCamera()
        self.iren_1.Initialize()
        self.iren_1.Start()


        self.PNG_Reader_2 = vtk.vtkPNGReader()
        self.PNG_Reader_2.SetNumberOfScalarComponents(1)
        self.PNG_Reader_2.SetFileDimensionality(3)
        self.PNG_Reader_2.SetDataExtent(0, 200, 0, 200, 0, 199)
        self.PNG_Reader_2.SetFilePrefix(r'C:\Users\vision2110\Desktop\chinghui\subject1\bone_resize\L2/')
        self.PNG_Reader_2.SetFilePattern("%s%d.png")
        self.PNG_Reader_2.Update()
        self.PNG_Reader_2.SetDataByteOrderToLittleEndian()

        self.PNG_contour_2 = vtk.vtkDiscreteMarchingCubes()
        self.PNG_contour_2.SetInputConnection(self.PNG_Reader_2.GetOutputPort())
        self.PNG_contour_2.ComputeNormalsOn()
        self.PNG_contour_2.SetValue(0, 255)

        self.PNG_sinc_2 = vtk.vtkWindowedSincPolyDataFilter()
        self.PNG_sinc_2.SetInputConnection(self.PNG_contour_2.GetOutputPort())
        self.PNG_sinc_2.SetNumberOfIterations(50)
        self.PNG_sinc_2.SetPassBand(0.003)

        PNG_mapper_2 = vtk.vtkPolyDataMapper()
        PNG_mapper_2.SetInputConnection(self.PNG_sinc_2.GetOutputPort())
        PNG_mapper_2.ScalarVisibilityOff()

        PNG_actor_2 = vtk.vtkActor()
        PNG_actor_2.SetMapper(PNG_mapper_2)

        PNG_renderer_2 = vtk.vtkRenderer()
        PNG_renderer_2.SetBackground([0.1, 0.1, 0.1])
        PNG_renderer_2.AddActor(PNG_actor_2)

        cameraR_2 = vtk.vtkCamera()
        cameraR_2.SetPosition(0, 1000, 0)
        cameraR_2.SetFocalPoint(0, 0, 0)
        cameraR_2.SetViewUp(0, 0, -1.0)

        self.ren_2.SetActiveCamera(cameraR_2)
        self.ren_2.AddActor(PNG_actor_2)
        self.ren_2.ResetCamera()
        self.iren_2.Initialize()
        self.iren_2.Start()



        self.PNG_Reader_3 = vtk.vtkPNGReader()
        self.PNG_Reader_3.SetNumberOfScalarComponents(1)
        self.PNG_Reader_3.SetFileDimensionality(3)
        self.PNG_Reader_3.SetDataExtent(0, 200, 0, 200, 0, 199)
        self.PNG_Reader_3.SetFilePrefix(r'C:\Users\vision2110\Desktop\chinghui\subject1\bone_resize\L3/')
        self.PNG_Reader_3.SetFilePattern("%s%d.png")
        self.PNG_Reader_3.Update()
        self.PNG_Reader_3.SetDataByteOrderToLittleEndian()

        self.PNG_contour_3 = vtk.vtkDiscreteMarchingCubes()
        self.PNG_contour_3.SetInputConnection(self.PNG_Reader_3.GetOutputPort())
        self.PNG_contour_3.ComputeNormalsOn()
        self.PNG_contour_3.SetValue(0, 255)

        self.PNG_sinc_3 = vtk.vtkWindowedSincPolyDataFilter()
        self.PNG_sinc_3.SetInputConnection(self.PNG_contour_3.GetOutputPort())
        self.PNG_sinc_3.SetNumberOfIterations(50)
        self.PNG_sinc_3.SetPassBand(0.003)

        PNG_mapper_3 = vtk.vtkPolyDataMapper()
        PNG_mapper_3.SetInputConnection(self.PNG_sinc_3.GetOutputPort())
        PNG_mapper_3.ScalarVisibilityOff()

        PNG_actor_3 = vtk.vtkActor()
        PNG_actor_3.SetMapper(PNG_mapper_3)

        PNG_renderer_3 = vtk.vtkRenderer()
        PNG_renderer_3.SetBackground([0.1, 0.1, 0.1])
        PNG_renderer_3.AddActor(PNG_actor_3)

        cameraR_3 = vtk.vtkCamera()
        cameraR_3.SetPosition(0, 1000, 0)
        cameraR_3.SetFocalPoint(0, 0, 0)
        cameraR_3.SetViewUp(0, 0, -1.0)

        self.ren_3.SetActiveCamera(cameraR_3)
        self.ren_3.AddActor(PNG_actor_3)
        self.ren_3.ResetCamera()
        self.iren_3.Initialize()
        self.iren_3.Start()







        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadcaseBTN.setText(_translate("MainWindow", "Load Case"))
        self.saveBTN.setText(_translate("MainWindow", "Save"))
        self.TransX_label.setText(_translate("MainWindow", "0"))
        self.TransY_label.setText(_translate("MainWindow", "0"))
        self.RotX_label.setText(_translate("MainWindow", "0"))
        self.RotY_label.setText(_translate("MainWindow", "0"))
        self.RotZ_label.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Translate X :"))
        self.label_2.setText(_translate("MainWindow", "Translate Y :"))
        self.label_3.setText(_translate("MainWindow", "Rotation X :"))
        self.label_4.setText(_translate("MainWindow", "Rotation Y :"))
        self.label_5.setText(_translate("MainWindow", "Rotation Z :"))
        self.updateBTN.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "Spine"))
        self.label_8.setText(_translate("MainWindow", "Fluoroscopy"))
        self.label_11.setText(_translate("MainWindow", "Translate Z :"))
        self.TransZ_label.setText(_translate("MainWindow", "0"))





if __name__ == '__main__':
    import sys
    import os
    os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_MainWindow()
    w = QtWidgets.QMainWindow()
    ex.setupUi(w)
    w.show()
    sys.exit(app.exec_())


